"""
copilot.py

Natural-language front end over the PV Elite database: routes a
question to either
  (a) SQL - exact numeric/factual lookups, comparisons, rankings
      (generated by the LLM from the real schema, validated as a
      read-only SELECT, then executed), or
  (b) vector search - "explain/summarize/compare" questions that need
      the report's own narrative text, not just extracted numbers.

Uses a local Ollama server (see _call_ollama) - no data leaves the
machine. Model is configurable; Qwen3 14B was the recommendation
discussed, but any Ollama-served instruct model works.

Deployment note: could not be run end-to-end in the build sandbox (no
route to ollama.com or a local Ollama server there - see the note at
the bottom of this file for exactly what was and wasn't verified).
"""
import json
import re
import sqlite3
import urllib.request
import urllib.error

import vector_db

OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "qwen3:14b"

# Statements a generated SQL query must never contain - this is the
# actual safety boundary for letting an LLM write and run SQL against a
# real database, so it's exhaustively tested (see the test block at the
# bottom of this file) independent of whether any LLM is available.
_FORBIDDEN_SQL_KEYWORDS = [
    "DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "ATTACH", "DETACH",
    "PRAGMA", "VACUUM", "REPLACE", "CREATE", "TRUNCATE", "EXEC",
]


def build_schema_description(schema_file="db_schema_sqlite.sql"):
    """
    Builds a compact, LLM-readable description of the frozen schema by
    reading the actual schema file - so this stays in sync with the
    real schema automatically rather than needing hand-maintenance
    every time a column is added.
    """
    with open(schema_file, "r") as f:
        sql = f.read()

    lines = ["Database schema (SQLite):"]
    for table_match in re.finditer(
        r"CREATE TABLE IF NOT EXISTS (\w+)\s*\((.*?)\n\);", sql, re.DOTALL
    ):
        table_name = table_match.group(1)
        body = table_match.group(2)
        cols = []
        for col_line in body.splitlines():
            col_line = col_line.strip().rstrip(",")
            m = re.match(r"^(\w+)\s+(TEXT|INTEGER|REAL)\b", col_line)
            if m:
                cols.append(m.group(1))
        lines.append(f"  {table_name}({', '.join(cols)})")
    return "\n".join(lines)


def _is_safe_select(sql):
    """
    Returns True only for a single, read-only SELECT statement. Used
    to validate any SQL an LLM generates before it's ever executed -
    this is the actual security boundary, so it rejects on the side of
    caution: multiple statements, comments (which could hide a second
    statement), and any keyword from _FORBIDDEN_SQL_KEYWORDS anywhere
    in the string, not just at the start.
    """
    if not sql or not sql.strip():
        return False
    cleaned = sql.strip().rstrip(";")
    if ";" in cleaned:
        return False  # no stacked statements
    if "--" in cleaned or "/*" in cleaned:
        return False  # no comments hiding additional content
    if not re.match(r"^\s*SELECT\b", cleaned, re.IGNORECASE):
        return False
    upper = cleaned.upper()
    for kw in _FORBIDDEN_SQL_KEYWORDS:
        if re.search(rf"\b{kw}\b", upper):
            return False
    return True


def _call_ollama(prompt, system=None, model=DEFAULT_MODEL, timeout=60):
    payload = {"model": model, "prompt": prompt, "stream": False}
    if system:
        payload["system"] = system
    req = urllib.request.Request(
        OLLAMA_URL, data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"}, method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())["response"]
    except urllib.error.URLError as exc:
        raise RuntimeError(
            f"Could not reach Ollama at {OLLAMA_URL} - is it running? ({exc})"
        )


def classify_question(question, model=DEFAULT_MODEL):
    """Returns 'SQL' or 'VECTOR'. Falls back to a simple keyword
    heuristic if Ollama isn't reachable, rather than failing outright."""
    system = (
        "Classify the user's question as exactly one word: SQL or VECTOR. "
        "SQL = the question asks for a specific number, comparison, ranking, "
        "material, dimension, or other fact that lives in a database. "
        "VECTOR = the question asks to explain, summarize, justify, or "
        "describe reasoning found in narrative report text. "
        "Respond with exactly one word."
    )
    try:
        result = _call_ollama(question, system=system, model=model).strip().upper()
        return "VECTOR" if "VECTOR" in result else "SQL"
    except RuntimeError:
        narrative_words = ["explain", "why", "summarize", "summarise", "describe",
                            "justify", "reasoning", "basis"]
        return "VECTOR" if any(w in question.lower() for w in narrative_words) else "SQL"


def answer_with_sql(question, db_path, schema_file="db_schema_sqlite.sql", model=DEFAULT_MODEL):
    schema = build_schema_description(schema_file)
    system = (
        f"{schema}\n\n"
        "Write ONE read-only SQLite SELECT statement (no other text, no markdown "
        "fences) that answers the user's question using this schema. "
        "Never write DROP/DELETE/UPDATE/INSERT/ALTER or any statement that "
        "isn't a SELECT."
    )
    sql = _call_ollama(question, system=system, model=model).strip()
    sql = re.sub(r"^```sql\s*|\s*```$", "", sql, flags=re.IGNORECASE).strip()

    if not _is_safe_select(sql):
        return {"error": "Generated query failed the safety check and was not run.", "sql": sql}

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        rows = [dict(r) for r in conn.execute(sql).fetchall()]
    finally:
        conn.close()
    return {"sql": sql, "rows": rows}


def answer_with_vector_search(question, db_path, chroma_path="./chroma_store",
                               project=None, tag_no=None, model=DEFAULT_MODEL):
    hits = vector_db.semantic_search(question, chroma_path=chroma_path,
                                      n_results=5, project=project, tag_no=tag_no)
    if not hits:
        return {"answer": "No relevant report sections found.", "sources": []}

    context = "\n\n".join(
        f"[{h['metadata']['tag_no']} - {h['metadata']['section_title']}]\n{h['text'][:1500]}"
        for h in hits
    )
    system = (
        "Answer the user's question using ONLY the report excerpts below. "
        "Cite which tag and section each fact comes from. If the excerpts "
        "don't contain the answer, say so rather than guessing.\n\n" + context
    )
    answer = _call_ollama(question, system=system, model=model)
    sources = [{"tag_no": h["metadata"]["tag_no"], "section": h["metadata"]["section_title"]} for h in hits]
    return {"answer": answer, "sources": sources}


def route_and_answer(question, db_path, schema_file="db_schema_sqlite.sql",
                      chroma_path="./chroma_store", model=DEFAULT_MODEL):
    route = classify_question(question, model=model)
    if route == "SQL":
        return {"route": "SQL", **answer_with_sql(question, db_path, schema_file, model)}
    return {"route": "VECTOR", **answer_with_vector_search(question, db_path, chroma_path, model=model)}


# ----------------------------------------------------------------------
# What was actually verified in the build sandbox vs. what needs
# verifying on a real deployment machine:
#
# VERIFIED (no LLM needed for these):
#   - _is_safe_select() against a wide range of safe and malicious SQL
#     strings (stacked statements, comments hiding a second statement,
#     forbidden keywords in various positions/cases) - see test block
#     run during development, reproducible independent of any model
#   - build_schema_description() against the real, frozen schema file
#
# NOT VERIFIED HERE (this sandbox has no route to ollama.com or a local
# Ollama server - needs testing on the real deployment machine):
#   - _call_ollama() actually reaching a real server
#   - classify_question() actual routing accuracy on real questions
#   - generated SQL actually being correct/useful (only that unsafe SQL
#     is correctly BLOCKED - not that safe, useful SQL is correctly
#     generated in the first place)
#   - vector-search answer quality (depends on vector_db.py's embedding
#     model, itself unverified for the same sandbox-network reason)
#
# First thing to run on the real machine: a handful of known-answer
# questions ("what's the fabricated weight of 121-D" - SQL path;
# "why was -12C chosen as MDMT for 121-D" - VECTOR path) and check both
# the routing decision and the actual answer by hand before trusting
# this for real use.
# ----------------------------------------------------------------------
